### ISSUE TITLE
Option to exclude API script

### ISSUE THREAD

**Issue by ithinkandicode** [AlexStack/Google-Recaptcha-to-any-form#4]
Hello! Thank you for making this, and especially updating it to work with v3.

Could you add an option to not echo the reCaptcha script please, i.e., this part:

`<script src='https://www.google.com/recaptcha/api.js'></script>`

The use case would be a WordPress site that may already include the script, e.g. with Contact Form 7.

And thank you again for your time!

**Comment by AlexStack** [comment]
Hi @ithinkandicode,

Exclude API script now works for recaptcha v2 now. What's you need to do is update to the latest version:
`composer clearcache && composer require alexstack/google-recaptcha-to-any-form
`
Then:

> Extra css class name for the Google Recaptcha area. For recaptcha v2: Add theme-dark if you want the dark theme instead of the light. Add no-api-js if you already import the recaptcha/api.js.

Cheers

**Comment by ithinkandicode** [comment]
Thank you :)
